// Generated by https://quicktype.io
import 'package:rca_app/iam/domain/domain.dart';
class RentingOrderItem {
    int? id;
    String? rentingPrice;
    String? rentingUnit;
    String? currency;
    String? startDate;
    String? endDate;
    int? vehicleId;
    String? state;
    int? requesterId;

  RentingOrderItem({
        this.id,
        this.rentingPrice,
        this.rentingUnit,
        this.currency,
        this.startDate,
        this.endDate,
        this.vehicleId,
        this.state,
        this.requesterId,
  });
}

