// Generated by https://quicktype.io
import 'package:rca_app/iam/domain/domain.dart';

class Vehicle {
  final String name;
  final String brand;
  final String model;
  final String integrity;
  final int state;
  final DateTime year;
  final int ownerId;
  final String image;
  final int stars;
  final double price;
  final String currency;
  final String timeUnit;
  final List<String> categories;

  Vehicle({
    required this.name,
    required this.brand,
    required this.model,
    required this.integrity,
    required this.state,
    required this.year,
    required this.ownerId,
    required this.image,
    required this.stars,
    required this.price,
    required this.currency,
    required this.timeUnit,
    required this.categories,
  });
}
